
variables:
    buildConfiguration: "Debug"
    testProject: "tests/MySample.Tests"
    solution: "MySample.sln"

trigger:
- master

pool:
  name: 'TestPool'
  demands: Agent.Name -equals jaba-windows

steps:
- task: UseDotNet@2
  displayName: Install .NET 2 sdk 
  inputs:
    packageType: sdk
    version: 2.2.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: SonarCloudPrepare@3
  displayName: 'coverage from: $(Build.SourcesDirectory)'
  inputs:
    SonarQube: 'SonarCloud'
    organization: 'sonarcloud-jaba'
    scannerMode: 'dotnet'
    projectKey: 'jabadrian_code-coverage-sample'
    projectName: 'code-coverage-sample'


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    publishTestResults: false
    arguments: '--logger trx --results-directory CodeCoverage --collect:"Code Coverage"'

- task: PublishTestResults@2
  displayName: 'Publicando test'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
    testRunTitle: 'testResult'

- task: SonarCloudAnalyze@3
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@3
  displayName: 'Publish Quality Gate Result'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: $(solution)
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact (WebApp.zip)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'