
variables:
    buildConfiguration: "Debug"
    testProject: "tests/MySample.Tests"
    solution: "MySample.sln"

trigger:
- master

pool:
  name: 'TestPool'
  demands: Agent.Name -equals jaba-windows

steps:
- task: UseDotNet@2
  displayName: Install .NET 2 sdk 
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: SonarCloudPrepare@3
  displayName: 'coverage from: $(Build.SourcesDirectory)'
  inputs:
    SonarQube: 'SonarCloud'
    organization: 'sonarcloud-jaba'
    scannerMode: 'dotnet'
    projectKey: 'jabadrian_code-coverage-sample'
    projectName: 'code-coverage-sample'
    extraProperties: 'sonar.flex.cobertura.reportPaths=$(Agent.TempDirectory)\**\coverage.opencover.xml'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests.csproj'
    publishTestResults: true
    arguments: '--configuration $(buildConfiguration) --no-build --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover,cobertura'

- script: |
    dotnet tool install dotnet-reportgenerator-globaltool --version 4.6.1 --tool-path .
    .\reportgenerator.exe "-reports:$(Agent.TempDirectory)\**\coverage.opencover.xml" "-targetdir:CodeCoverage" "-reporttypes:Cobertura;HTMLInline;HTMLChart"
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: Run Reportgenerator on Windows

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
- task: SonarCloudAnalyze@3
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@3
  displayName: 'Publish Quality Gate Result'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: $(solution)
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact (WebApp.zip)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'